name: ci rails
on: [push, pull_request]
jobs: 
  build:
    runs-on: ubuntu-latest
    
    services: 
      db:
        image: mysql:5.7
        nv:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: app_ci
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD:
        ports:
          - "3306:3306"

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 2.7
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: 2.7
          bundler: default
          bundler-cache: true

      - name: Run tests
        env: 
          RAILS_ENV: test
          DATABASE_PORT: 3306

        run: | 
          gem install bundler
          bundle install 
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails test

          
          
