name: ci rails
on: [push, pull_request]
jobs: 
  build:
    runs-on: ubuntu-latest
    
    services: 
      db:
        image: mysql:5.7
        ports: ['3307:3306']
        env: 
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_ci
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 2.7
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: 2.7
          bundler: default
          bundler-cache: true

      - name: Run tests
        env: 
          RAILS_ENV: test
          DATABASE_PORT: 3307
        run: | 
          cd bin
          rails db:create
          rails db:schema:load
          rails test

          
          
