name: ci rails
on: [push, pull_request]
jobs: 
  build:
    runs-on: ubuntu-latest
    
    services: 
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root 
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 2.7
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: 2.7
          bundler: default
          bundler-cache: true

      - name: Run tests
        env: 
          RAILS_ENV: test
          DATABASE_PORT: 3306
          DB_PASSWORD: root

        run: | 
          gem install bundler
          bundle install 
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails test

          
          
